name: Continous integration

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"
    paths:
        - '.github/workflows/**'
        - 'src/**'
        - 'cargo.toml'
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: cargo clippy 
    - name: Run tests
      run: cargo test --verbose
