name: Continous Integration

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"
    paths:
        - '.github/workflows/**'
        - 'src/**'
        - 'cargo.toml'
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build with cargo
      run: cargo build --verbose
    - name: Lint with clippy
      run: cargo clippy --all-targets --all-features
    - name: Run tests with cargo
      run: cargo test --verbose
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
