name: Continous Integration

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"
    paths:
        - '.github/workflows/**'
        - 'src/**'
        - 'cargo.toml'
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build with cargo
      run: cargo build --verbose
    - name: Check formatting with fmt
      run: cargo fmt --all -- --check
    - name: Lint with clippy
      run: cargo clippy --all-targets --all-features
    - name: Setup cargo-tarpaulin
      run: |
        curl -s https://api.github.com/repos/xd009642/tarpaulin/releases/latest | \
          grep "browser_download_url.*x86_64-unknown-linux-musl.tar.gz" | cut -d : -f 2,3 | tr -d \" | wget -qi -
        tar -xzf cargo-tarpaulin-*.tar.gz
        mv cargo-tarpaulin ~/.cargo/bin/
    - name: Run tests with tarpaulin
      run: cargo tarpaulin --out Xml --verbose
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: cobertura.xml
        flags: unittests
        name: code-coverage-report
        fail_ci_if_error: true
